import { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const AllVariants: Story;
export declare const AllSizes: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
